name: Deploy
run-name: Peanut Gallery CDK Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: pwd
      - run: ls
      - name: authenticate with aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::256470578440:role/PeanutGalleryGithubActionsCDKDeployer
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
