name: Deploy
run-name: Peanut Gallery CDK Deploy
on: [push]
jobs:
  CDK-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
      - run: ls -a
      - run: pwd
      - name: diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_DEFAULT_REGION: 'us-east-2'
